### PR TITLE
add OWNERS.md

### PR DESCRIPTION
**Pull request by displague**
## Description

Adds an OWNERS.md file to define the community make-up and roles.

This could be expanded in the future with more community details about how to participate in the community and increase responsibilities.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by displague** [comment]
Should we have meeting attendance requirements too?

**Comment by mmlb** [comment]
Please do [one-sentence-per-line](https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line). I like to read markdown in source form and this layout makes it quite difficult.

**Comment by displague** [comment]
@mmlb 

We don't have a documentation style-guide in place. I think an issue or PR on that topic would be the best place to have this discussion 😄.

That aside, I don't know which is the more popular opinion [here](https://news.ycombinator.com/item?id=4642395).

I can [link](https://nickjanetakis.com/blog/80-characters-per-line-is-a-standard-worth-sticking-to-even-today) to [posts](https://coderwall.com/p/sgv6aa/markdown-long-urls-that-play-nicely-with-80-character-line-length) [with](https://graphicdesign.stackexchange.com/questions/13724/recommended-column-width-for-text-reading-digital-vs-printed) the [opposite](https://cirosantilli.com/markdown-style-guide/#line-wrapping) [view](https://github.com/carwin/markdown-styleguide#basic-conventions-for-markdown-files) point on [readability](https://www.viget.com/articles/the-line-length-misconception/) and fixed-length lines. License files (markdown or others) tend to carry the 80 character column width. I encounter and use the [Markdown Linter](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md013---line-length) in many places, including [VS Code](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint).



In my HTML editing days, I preferred one *paragraph* per line, and I preferred using the IDE to soft-break text.

My preference changed when I started working with Go and Markdown, especially in Github where the review pane needs to be horizontally scrolled beyond 80 characters (_Update: no longer the case?_ 🤔).  The viewer or maintainer is not always behind an editor or IDE where width settings can be controlled.


The column width changes nothing for readers of the rendered documents. This mostly affects the people that manage and review documents.


Would it help if I adopted the citation style of markdown links? _(Update: Applied)._
 <http://www.rubycoloredglasses.com/2017/11/markdown-links-80-character-line-length/>

**Review by gianarb — APPROVED** [review]

**Comment by DailyAlice** [comment]
> Please do [one-sentence-per-line](https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line). I like to read markdown in source form and this layout makes it quite difficult.

As someone who also likes to read the markdown source, I find one sentence per line more difficult to read. I'm fine with the 80 column-width or with no fixed column-width. But reading something that is one-sentence per line is very difficult.

**Review by DailyAlice — APPROVED** [review]
I'm  going to approve and merge since this PR has been open for 7 days with no other discussion other than formatting.

**Comment by mmlb** [comment]
@displague sorry for not replying sooner, I'm going through my tabs and ran across this again.

> @mmlb
> 
> We don't have a documentation style-guide in place. I think an issue or PR on that topic would be the best place to have this discussion smile.

Agree. I will do so and embed this content and my thoughts to start the conversation.

**Pull request merged**
